{"uuid":"b45eba61-9202-4a8d-a75d-a349a06ab560","historyId":"e3dced278699897db38e1d57a1ba4e8e","fullName":"Tests.AuthTests.validSignUpTest","labels":[{"name":"package","value":"Tests.AuthTests"},{"name":"testClass","value":"Tests.AuthTests"},{"name":"testMethod","value":"validSignUpTest"},{"name":"parentSuite","value":"Full Test Suite"},{"name":"suite","value":"All Tests"},{"name":"subSuite","value":"Tests.AuthTests"},{"name":"host","value":"Sondoss-MacBook-Pro.local"},{"name":"thread","value":"7501@Sondoss-MacBook-Pro.local.main(1)"},{"name":"framework","value":"testng"},{"name":"language","value":"java"},{"name":"story","value":"Sign up with valid data"},{"name":"feature","value":"Sign Up & Login"},{"name":"epic","value":"Authentication Module"},{"name":"severity","value":"critical"}],"links":[],"name":"validSignUpTest","status":"failed","statusDetails":{"known":false,"muted":false,"flaky":false,"message":"Sign up failed, alert message is not as expected. expected [Sign up successful.] but found [This user already exist.]","trace":"java.lang.AssertionError: Sign up failed, alert message is not as expected. expected [Sign up successful.] but found [This user already exist.]\n\tat org.testng.Assert.fail(Assert.java:111)\n\tat org.testng.Assert.failNotEquals(Assert.java:1590)\n\tat org.testng.Assert.assertEqualsImpl(Assert.java:150)\n\tat org.testng.Assert.assertEquals(Assert.java:132)\n\tat org.testng.Assert.assertEquals(Assert.java:656)\n\tat Tests.AuthTests.validSignUpTest(AuthTests.java:35)\n\tat java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:580)\n\tat org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)\n\tat org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)\n\tat org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)\n\tat org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)\n\tat org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)\n\tat org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)\n\tat org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)\n\tat org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)\n\tat java.base/java.util.ArrayList.forEach(ArrayList.java:1596)\n\tat org.testng.TestRunner.privateRun(TestRunner.java:741)\n\tat org.testng.TestRunner.run(TestRunner.java:616)\n\tat org.testng.SuiteRunner.runTest(SuiteRunner.java:421)\n\tat org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)\n\tat org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)\n\tat org.testng.SuiteRunner.run(SuiteRunner.java:312)\n\tat org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)\n\tat org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)\n\tat org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)\n\tat org.testng.TestNG.runSuitesLocally(TestNG.java:1208)\n\tat org.testng.TestNG.runSuites(TestNG.java:1112)\n\tat org.testng.TestNG.run(TestNG.java:1079)\n\tat com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:65)\n\tat com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)\n"},"stage":"finished","description":"Verify valid sign up with new username and password display alert message 'Sign up successful.'","steps":[],"attachments":[{"name":"logs.log","source":"b546afdf-d104-4daf-b255-ca50ed849604-attachment.txt","type":"text/plain"},{"name":"validSignUpTest","source":"28f671b8-4813-4b81-82d8-da76f5d1bf6f-attachment"}],"parameters":[],"start":1754823369384,"stop":1754823372310}